<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[RaghavTest Runner started]]>
    </line>
    <line>
      <![CDATA[Login Page is Displayed, PASS]]>
    </line>
    <line>
      <![CDATA[verifyTasks method started]]>
    </line>
    <line>
      <![CDATA[Enter Time Track Page is Displayed, PASS]]>
    </line>
    <line>
      <![CDATA[verifyTasks method FAILED]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-13T12:32:29 IST" name="Suite" finished-at="2022-07-13T12:32:47 IST" duration-ms="18082">
    <groups>
    </groups>
    <test started-at="2022-07-13T12:32:29 IST" name="RaghavTest" finished-at="2022-07-13T12:32:47 IST" duration-ms="18082">
      <class name="com.actitime.tasks.VerifyTasksTest">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:com.actitime.tasks.VerifyTasksTest@48e4374]" started-at="2022-07-13T12:32:29 IST" name="openBrowser" finished-at="2022-07-13T12:32:40 IST" duration-ms="10605" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Login Page is Displayed, PASS]]>
            </line>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="verifyTasks()[pri:0, instance:com.actitime.tasks.VerifyTasksTest@48e4374]" started-at="2022-07-13T12:32:40 IST" name="verifyTasks" finished-at="2022-07-13T12:32:47 IST" duration-ms="7137" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.actitime.tasks.VerifyTasksTest.verifyTasks(VerifyTasksTest.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[verifyTasks method started]]>
            </line>
            <line>
              <![CDATA[Enter Time Track Page is Displayed, PASS]]>
            </line>
            <line>
              <![CDATA[verifyTasks method FAILED]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyTasks -->
      </class> <!-- com.actitime.tasks.VerifyTasksTest -->
    </test> <!-- RaghavTest -->
  </suite> <!-- Suite -->
</testng-results>
